service: sample-app
provider:
  name: aws
  runtime: nodejs16.x
  stage: prd
  region: us-east-1
  memorySize: 128
functions:
  api-eventos:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true